title: "My Blog"
baseurl: "/blog"
url: "https://dazstaffs.github.io/"

# Site author
author: "Darren Stafford"
author_bio: "I write about web development, design, and other interesting topics."

# Social media
social:
  twitter: "#"
  github: "#"
  linkedin: "#"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed
