title: "Darren Stafford - Blog"
baseurl: "/blog"
url: "https://dazstaffs.github.io/"

# Site author
author: "Darren Stafford"
author_bio: "I write about software engineering, the insurance industry, leading and building great teams and key takeaways from non-fiction career-based books I have read, and exams I have taken"

# Social media
social:
  github: "https://github.com/dazstaffs"
  linkedin: "https://www.linkedin.com/in/darren-stafford"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

collections:
  tags:
    output: true
    permalink: /tags/:name/
